### ISSUE TITLE
gradle builde 编译时找不到build.js

### ISSUE THREAD

**Issue by shyding** [sxfad/porter#16]
Error: Cannot find module 'C:\Users\root\git\porter\porter-ui\builder\build.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.Module._load (internal/modules/cjs/loader.js:508:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:754:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)

**Comment by zhangkewei** [comment]
报错源于
![image](https://user-images.githubusercontent.com/5011406/58377438-0d44d880-7fb3-11e9-9cca-a028d8c439bd.png)

porter-ui作为submodule被引入porter项目

编译前需要执行submodule的更新
``
   git submodule init
   git submodule update
``

如果仍然没有下载到porter-ui的代码，可直接将https://github.com/sxfad/porter-ui的代码复制到相应目录，复制时注意版本号。
