### ISSUE TITLE
编译yporter-boot 启动时报错,怎么解决

### ISSUE THREAD

**Issue by shyding** [sxfad/porter#17]
ava.lang.Error: Unresolved compilation problems: 
	The import org.apache.kafka cannot be ava.lang.Error: Unresolved compilation problems: 
	The import org.apache.kafka cannot be resolved
	The import org.apache.kafka cannot be resolved
	The import org.apache.kafka cannot be resolved
	The import org.apache.kafka cannot be resolved
	The import org.apache.kafka cannot be resolved
	The import org.apache.kafka cannot be resolved
	The import org.apache.kafka cannot be resolved
	Producer cannot be resolved to a type
	PartitionInfo cannot be resolved to a type
	ProducerConfig cannot be resolved to a variable
	ProducerConfig cannot be resolved to a variable
	ProducerConfig cannot be resolved to a variable
	StringSerializer cannot be resolved to a type
	ProducerConfig cannot be resolved to a variable
	StringSerializer cannot be resolved to a type
	ProducerConfig cannot be resolved to a variable
	ProducerConfig cannot be resolved to a variable
	Producer cannot be resolved to a type
	KafkaProducer cannot be resolved to a type
	PartitionInfo cannot be resolved to a type
	Producer cannot be resolved to a type
	Producer cannot be resolved to a type
	Producer cannot be resolved to a type
	Producer cannot be resolved to a type
	Producer cannot be resolved to a type
	ProducerRecord cannot be resolved to a type
	ProducerRecord cannot be resolved to a type
	ProducerRecord cannot be resolved to a type
	ProducerRecord cannot be resolved to a type
	ProducerRecord cannot be resolved to a type
	ProducerRecord cannot be resolved to a type
	ProducerRecord cannot be resolved to a type
	ProducerRecord cannot be resolved to a type
	ProducerRecord cannot be resolved to a type
	Producer cannot be resolved to a type
	RecordMetadata cannot be resolved to a type
	ProducerRecord cannot be resolved to a type
	Producer cannot be resolved to a type
	RecordMetadata cannot be resolved to a type
	Producer cannot be resolved to a type
	Producer cannot be resolved to a type
	PartitionInfo cannot be resolved to a type
	PartitionInfo cannot be resolved to a type

	at cn.vbill.middleware.porter.common.client.impl.KafkaProduceClient.<init>(KafkaProduceClient.java:30)
	at cn.vbill.middleware.porter.common.client.AbstractClient.getClient(AbstractClient.java:165)
	at cn.vbill.middleware.porter.common.cluster.impl.zookeeper.ZookeeperClusterProvider.initClient(ZookeeperClusterProvider.java:73)
	at cn.vbill.middleware.porter.common.cluster.impl.AbstractClusterProvider.initialize(AbstractClusterProvider.java:237)
	at cn.vbill.middleware.porter.common.cluster.impl.AbstractClusterProvider.start(AbstractClusterProvider.java:205)
	at cn.vbill.middleware.porter.common.cluster.ClusterProviderProxy.initialize(ClusterProviderProxy.java:56)
	at cn.vbill.middleware.porter.boot.NodeBootApplication.main(NodeBootApplication.java:112)

2019-05-26 14:32:00.216  INFO 4236 --- [Thread-4] o.s.s.concurrent.ThreadPoolTaskExecutor  : Shutting down ExecutorService 'applicationTaskExecutor'resolved
	The import org.apache.kafka cannot be resolved
	The import org.apache.kafka cannot be resolved
	The import org.apache.kafka cannot be resolved
	The import org.apache.kafka cannot be resolved
	The import org.apache.kafka cannot be resolved
	The import org.apache.kafka cannot be resolved
	Producer cannot be resolved to a type
	PartitionInfo cannot be resolved to a type
	ProducerConfig cannot be resolved to a variable
	ProducerConfig cannot be resolved to a variable
	ProducerConfig cannot be resolved to a variable
	StringSerializer cannot be resolved to a type
	ProducerConfig cannot be resolved to a variable
	StringSerializer cannot be resolved to a type
	ProducerConfig cannot be resolved to a variable
	ProducerConfig cannot be resolved to a variable
	Producer cannot be resolved to a type
	KafkaProducer cannot be resolved to a type
	PartitionInfo cannot be resolved to a type
	Producer cannot be resolved to a type
	Producer cannot be resolved to a type
	Producer cannot be resolved to a type
	Producer cannot be resolved to a type
	Producer cannot be resolved to a type
	ProducerRecord cannot be resolved to a type
	ProducerRecord cannot be resolved to a type
	ProducerRecord cannot be resolved to a type
	ProducerRecord cannot be resolved to a type
	ProducerRecord cannot be resolved to a type
	ProducerRecord cannot be resolved to a type
	ProducerRecord cannot be resolved to a type
	ProducerRecord cannot be resolved to a type
	ProducerRecord cannot be resolved to a type
	Producer cannot be resolved to a type
	RecordMetadata cannot be resolved to a type
	ProducerRecord cannot be resolved to a type
	Producer cannot be resolved to a type
	RecordMetadata cannot be resolved to a type
	Producer cannot be resolved to a type
	Producer cannot be resolved to a type
	PartitionInfo cannot be resolved to a type
	PartitionInfo cannot be resolved to a type

	at cn.vbill.middleware.porter.common.client.impl.KafkaProduceClient.<init>(KafkaProduceClient.java:30)
	at cn.vbill.middleware.porter.common.client.AbstractClient.getClient(AbstractClient.java:165)
	at cn.vbill.middleware.porter.common.cluster.impl.zookeeper.ZookeeperClusterProvider.initClient(ZookeeperClusterProvider.java:73)
	at cn.vbill.middleware.porter.common.cluster.impl.AbstractClusterProvider.initialize(AbstractClusterProvider.java:237)
	at cn.vbill.middleware.porter.common.cluster.impl.AbstractClusterProvider.start(AbstractClusterProvider.java:205)
	at cn.vbill.middleware.porter.common.cluster.ClusterProviderProxy.initialize(ClusterProviderProxy.java:56)
	at cn.vbill.middleware.porter.boot.NodeBootApplication.main(NodeBootApplication.java:112)

2019-05-26 14:32:00.216  INFO 4236 --- [Thread-4] o.s.s.concurrent.ThreadPoolTaskExecutor  : Shutting down ExecutorService 'applicationTaskExecutor'

**Comment by zhangkewei** [comment]
检查你的IDE导入项目后的模块依赖是否正常
